services:
  mysql:
    image: mysql:latest
    container_name: badge-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    networks:
      - webnet

  nginx:
    container_name: badge-nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - media-data:/app/media
      - static-data:/app/static
    expose:
      - "80"
      - "443"
    depends_on:
      - django
    networks:
      - webnet
    restart: on-failure

  django:
    build: ./server
    container_name: badge-django
    command: ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./server:/app
      - ./log:/app/log
      - static-data:/app/static
      - media-data:/app/media
    ports:
      - "8000:8000"
    networks:
      - webnet
    depends_on:
      mysql:
        condition: service_healthy

  next:
    build: ./client
    container_name: badge-next
    command: ./entrypoint.sh
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - django
    

networks:
  webnet:
    driver: bridge

volumes:
  db-data:
  static-data:
    driver: local
  media-data:
    driver: local
