# Generated by Django 5.1 on 2024-08-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('vip', 'VIP'), ('blocked', 'Blocked')], default='new', max_length=10),
        ),
    ]
