
FROM python:3.11

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r /app/requirements.txt

# Expose the port the app runs on
EXPOSE 8000

# Run the Django development server
ENTRYPOINT ["/app/entrypoint.sh"]