# Generated by Django 5.1 on 2024-08-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail',
            new_name='Mails',
        ),
    ]
